### ISSUE TITLE
CSRF Token does not attach to session

### ISSUE THREAD

**Issue by Arthurdb1999** [wtforms/flask-wtf#494]
I'm using Flask as an API and ReactJS for my front-end, and followed the [CSRF Protection Docs with Javascript Requests (Axios)](https://flask-wtf.readthedocs.io/en/0.15.x/csrf/#javascript-requests).

#### Please follow my Init App file to see my code: <https://gist.github.com/Arthurdb1999/c72226800f19d6c8553d216fb1720900>

When making a request, the following Exception is logged:

## Traceback:

```Traceback (most recent call last):
  File "C:\Users\arthur\Documents\Arthur\MyApp\venv\Lib\site-packages\flask_wtf\csrf.py", line 261, in protect
    validate_csrf(self._get_csrf_token())
  File "C:\Users\arthur\Documents\Arthur\MyApp\venv\Lib\site-packages\flask_wtf\csrf.py", line 103, in validate_csrf
    raise ValidationError("The CSRF session token is missing.")
wtforms.validators.ValidationError: The CSRF session token is missing.    

During handling of the above exception, another exception occurred:       

Traceback (most recent call last):
  File "C:\Users\arthur\Documents\Arthur\MyApp\venv\Lib\site-packages\flask\app.py", line 1497, in full_dispatch_request
    rv = self.preprocess_request()
  File "C:\Users\arthur\Documents\Arthur\MyApp\venv\Lib\site-packages\flask\app.py", line 1838, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Users\arthur\Documents\Arthur\MyApp\venv\Lib\site-packages\flask_wtf\csrf.py", line 229, in csrf_protect
    self.protect()
  File "C:\Users\arthur\Documents\Arthur\MyApp\venv\Lib\site-packages\flask_wtf\csrf.py", line 264, in protect
    self._error_response(e.args[0])
  File "C:\Users\arthur\Documents\Arthur\MyApp\venv\Lib\site-packages\flask_wtf\csrf.py", line 307, in _error_response
    raise CSRFError(reason)
flask_wtf.csrf.CSRFError: 400 Bad Request: The CSRF session token is missing.
```

So I started to debug the error at [csrf.py](https://github.com/wtforms/flask-wtf/blob/main/src/flask_wtf/csrf.py) file in the flask-wtf folder of my virtual environment and found out that the `generate_csrf()` function is never called, and that's why I'm posting this as a bug report. Because of that, I think the token will never attach to `session`.

I'm sending the following header to the API: `X-CSRFToken: {{ csrf_token() }}`, and also tried to put the whole token on it (which wouldn't be secure).

Am I doing something wrong or is this really a bug to be fixed? I can give any other environment info if needed.

Environment:

- Python version: 3.9.0
- Flask-WTF version: 0.15.1 or 1.0.0 (error raises on both)
- Flask version: 2.0.0

**Comment by sekirkity** [comment]
HI @Arthurdb1999 , I was having a somewhat similar issue to you, and it ended up being related to using multiple uwsgi worker processes. I would recommend checking to see if the CSRF signed token is present in g for the requests that fail, flask-wtforms will not attach a session token if the signed token in g is present (refer to csrf.py for more info). I'm not exactly sure why this issue was occurring when using multiple worker processes, but I assume it's related to the shared application context. I resolved this issue by moving to a single uwsgi worker process with multithreading. Good luck!

**Comment by eljeffeg** [comment]
I think this might describe what I'm seeing https://github.com/wtforms/flask-wtf/issues/424
I get a session csrf_token, but it's not in the format that `protect()` expects, resulting in failure to validate.

**Comment by michaels-atbay** [comment]
Happens to me as well. Any news on this?
